export const LOGIN_ACTION = 'LOGIN_ACTION'
export const CREATE_EMPLOYEE = 'CREATE_EMPLOYEE';
export const FETCH_EMPLOYEES = 'FETCH_EMPLOYEES';
export const SET_EMPLOYEES = 'SET_EMPLOYEES';
export const FETCH_EMPLOYEE_BY_ID = 'FETCH_EMPLOYEE_BY_ID';
export const SET_EMPLOYEE_BY_ID = 'SET_EMPLOYEE_BY_ID';
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
export const DELETE_EMPLOYEE_SUCCESS = 'DELETE_EMPLOYEE_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const FETCH_TOTAL_EMPLOYEES = 'FETCH_TOTAL_EMPLOYEES';
export const SET_TOTAL_EMPLOYEES = 'SET_TOTAL_EMPLOYEES';

